name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: nugrahaddict
          POSTGRES_PASSWORD: P@ssw0rd123
          POSTGRES_DB: crud_db
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend/vue-app
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test # Assuming you have tests configured

      - name: Run frontend build
        run: |
          cd frontend/vue-app
          npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy backend
        run: |
          # You can define your deployment steps here, e.g., pushing images to Docker Hub
